tools:
    external_code_coverage: true
    php_mess_detector:
        enabled: true
    php_analyzer:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    sensiolabs_security_checker:
        enabled: true
    php_pdepend:
        enabled: true
