language: php

php:
   - 5.3
   - 5.4
   - 5.5
   - 5.6
   - hhvm

env:
   - SYMFONY_VERSION=2.1.*
   - SYMFONY_VERSION=2.2.*
   - SYMFONY_VERSION=2.3.*
   - SYMFONY_VERSION=2.4.*

before_script:
   - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --dev
   - composer update --prefer-dist --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text

notifications:
   email:
      - php@h4cc.de
